// examples/react/react-app/src/shared/ui/log/log.tsx
import './log.css';

export interface IPrintLogProps {
  items: unknown[]
}

export function PrintLog({
  items
}: IPrintLogProps) {
  return (
    <div className="logs">
      {items.map((log, index) => {
        return (
          <div key={index} className="logs__item log">
            { typeof log  === 'string' ? log : JSON.stringify(log, null, 2) }
          </div>
        );
      })}
    </div>
  );
}

// examples/vue/app/src/shared/ui/log/log.vue
<!-- eslint-disable vue/multi-word-component-names -->
<script setup lang="ts">
interface IPrintLogProps {
  items: unknown[]
}

const props = defineProps<IPrintLogProps>();
</script>

<template>
  <div class="logs">
    <template 
      v-for="item in items"
      :key="item"
    >
      <div class="logs__item log">
        {{ typeof item  === 'string' ? item : JSON.stringify(item, null, 2) }}
      </div>
    </template>
  </div> 
</template>

<style>
@import './log.css';
</style>
