// examples/react/react-app/src/App.tsx
/* eslint-disable complexity */
import './App.css';

import { useState } from 'react';

import {
  MetaApiStream,
  MetaApiRpc,
  RiskManagementPeriodStatisticsStream,
  RiskManagementEquityChartStream,
  RiskManagementEqulityBalance,
  RiskManagementEquityTracking,
  HistoricalGetCandles,
  HistoricalGetTicks,
  CopyFactoryExternalSignal,
  CopyFactoryStopoutListener,
  CopyFactoryCopyTrade,
  CopyFactoryStrategyTransactionListener,
  CopyFactoryUserLogListener,
  CopyFactorySubscriberTransactionListener,
  CopyFactorySubscriberUserLogListener,
  CopyFactoryTelegram,
  MetaStatsGetOpenTrades,
  MetaStatsGetTrades,
  MetaStatsGetMetrics,
  StreamQuotes
} from './components';

import { Toggler } from './shared';

interface IExample {
  name: string
  items: string[]
}

const examples: IExample[] = [
  {
    name: 'MetaApi',
    items: [
      'meta-api.stream',
      'meta-api.rpc',
      'historical.get-candles',
      'historical.get-ticks',
      'stream-quotes'
    ]
  }, {
    name: 'Risk Management',
    items: [
      'risk-management.period-statistics-stream', 
      'risk-management.equity-chart-stream', 
      'risk-management.equlity-balance', 
      'risk-management.equity-tracking'
    ]
  }, {
    name: 'Copy Factory',
    items: [
      'copy-factory.external-signal',
      'copy-factory.stopout-listener',
      'copy-factory.copy-trade',
      'copy-factory.strategy-transaction-listener',
      'copy-factory.strategy-user-log-listener',
      'copy-factory.subscriber-transaction-listener',
      'copy-factory.subscriber-user-log-listener',
      'copy-factory.telegram'
    ]
  }, {
    name: 'Meta Stats',
    items: [
      'meta-stats.get-open-trades',
      'meta-stats.get-trades',
      'meta-stats.get-metrics',
    ]
  }
];

/* For CopyFactory */
const providerAccountId = import.meta.env.VITE_PROVIDER_ACCOUNT_ID || 'your-provider-account-id';
const subscriberAccountId = import.meta.env.VITE_SUBSCRIBER_ACCOUNT_ID || 'your-subscriber-account-id';
const strategyId = import.meta.env.VITE_STRATEGY_ID || 'your-strategy-id';
const botToken = import.meta.env.VITE_TELEGRAM_BOT_TOKEN || 'your-telegram-bot-token';
const chatId = import.meta.env.VITE_TELEGRAM_CHAT_ID || 'your-telegram-chat-id';

/* For MetaApi */
const accountId = import.meta.env.VITE_ACCOUNT_ID || 'your-metaapi-account-id';
const token = import.meta.env.VITE_TOKEN || 'your-metaapi-token';

/* Meta */
const domain = import.meta.env.VITE_DOMAIN || 'agiliumtrade.agiliumtrade.ai';
const symbol = import.meta.env.VITE_SYMBOL || 'EURUSD';

function App() {
  const [activeExample, setActiveExamples] = useState<string>('metaapi.rpc');
  
  return (
    <div className="App">
      <h1>MetaApi + React</h1>
      
      <div className="togglers">
        {examples.map(example => <Toggler key={example.name}
          className="togglers__item"
          onClickHandler={(value: string) => setActiveExamples(value)} 
          {...example}
          activeItem={activeExample}
        />)}
      </div>

      <div className="component">
        { (activeExample === 'meta-api.stream') && 
          <MetaApiStream {...{ accountId, domain, token }} /> }
        { (activeExample === 'meta-api.rpc') && 
          <MetaApiRpc {...{ accountId, domain, token }} /> }

        { (activeExample === 'risk-management.period-statistics-stream') && 
          <RiskManagementPeriodStatisticsStream {...{ accountId, domain, token }} /> }
        { (activeExample === 'risk-management.equity-chart-stream') && 
          <RiskManagementEquityChartStream {...{ accountId, domain, token }} /> }
        { (activeExample === 'risk-management.equlity-balance') && 
          <RiskManagementEqulityBalance {...{ accountId, domain, token }} /> }
        { (activeExample === 'risk-management.equity-tracking') && 
          <RiskManagementEquityTracking {...{ accountId, domain, token }} /> }

        { (activeExample === 'historical.get-candles') && 
          <HistoricalGetCandles {...{ token, accountId, symbol, domain }} /> }
        { (activeExample === 'historical.get-ticks') && 
          <HistoricalGetTicks {...{ token, accountId, symbol, domain }} /> }

        { (activeExample === 'copy-factory.external-signal') && 
          <CopyFactoryExternalSignal {...{ providerAccountId, subscriberAccountId, token, domain }} /> }
        { (activeExample === 'copy-factory.stopout-listener') && 
          <CopyFactoryStopoutListener {...{ token, domain }} /> }
        { (activeExample === 'copy-factory.copy-trade') && 
          <CopyFactoryCopyTrade {...{ token, providerAccountId, subscriberAccountId, domain }} /> }
        { (activeExample === 'copy-factory.strategy-transaction-listener') && 
          <CopyFactoryStrategyTransactionListener {...{ token, strategyId, domain }} /> }
        { (activeExample === 'copy-factory.strategy-user-log-listener') && 
          <CopyFactoryUserLogListener {...{ token, strategyId, domain }} /> }
        { (activeExample === 'copy-factory.subscriber-transaction-listener') && 
          <CopyFactorySubscriberTransactionListener {...{ token, subscriberAccountId, domain }} /> }
        { (activeExample === 'copy-factory.subscriber-user-log-listener') && 
          <CopyFactorySubscriberUserLogListener {...{ token, subscriberAccountId, domain }} /> }
        { (activeExample === 'copy-factory.telegram') && 
          <CopyFactoryTelegram {...{ token, domain, botToken, chatId, providerAccountId }} /> }

        { (activeExample === 'meta-stats.get-open-trades') && 
          <MetaStatsGetOpenTrades {...{ token, accountId, domain }} /> }
        { (activeExample === 'meta-stats.get-trades') && 
          <MetaStatsGetTrades {...{ token, accountId, domain }} /> }
        { (activeExample === 'meta-stats.get-metrics') && 
          <MetaStatsGetMetrics {...{ token, accountId, domain }} /> }        

        { (activeExample === 'stream-quotes') && 
          <StreamQuotes {...{ token, accountId, domain, symbol }} /> }        
      </div> 
    </div>
  );
}

export default App;

// examples/angular/angular-app/src/app/app.component.ts
import { BehaviorSubject } from 'rxjs';
import { Component } from '@angular/core';
import { environment } from './environment/environment';

interface IExample {
  name: string
  items: string[]
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  activeExample$ = new BehaviorSubject<string>('meta-api.rpc');
  setActiveExample = (example: string) => {
    this.activeExample$.next(example);
  }

  examples: IExample[] = [
    {
      name: 'MetaApi',
      items: [
        'meta-api.stream',
        'meta-api.rpc',
        'historical.get-candles',
        'historical.get-ticks',
        'stream-quotes'
      ]
    }, {
      name: 'Risk Management',
      items: [
        'risk-management.period-statistics-stream', 
        'risk-management.equity-chart-stream', 
        'risk-management.equlity-balance', 
        'risk-management.equity-tracking'
      ]
    }, {
      name: 'Copy Factory',
      items: [
        'copy-factory.external-signal',
        'copy-factory.stopout-listener',
        'copy-factory.copy-trade',
        'copy-factory.strategy-transaction-listener',
        'copy-factory.strategy-user-log-listener',
        'copy-factory.subscriber-transaction-listener',
        'copy-factory.subscriber-user-log-listener',
        'copy-factory.telegram'
      ]
    }, {
      name: 'Meta Stats',
      items: [
        'meta-stats.get-open-trades',
        'meta-stats.get-trades',
        'meta-stats.get-metrics',
      ]
    }
  ];

  /* For CopyFactory */
  providerAccountId = environment.PROVIDER_ACCOUNT_ID || 'your-provider-account-id';
  subscriberAccountId = environment.SUBSCRIBER_ACCOUNT_ID || 'your-subscriber-account-id';
  strategyId = environment.STRATEGY_ID || 'your-strategy-id';
  botToken = environment.TELEGRAM_BOT_TOKEN || 'your-telegram-bot-token';
  chatId = environment.TELEGRAM_CHAT_ID || 'your-telegram-chat-id';

  /* For MetaApi */
  accountId = environment.ACCOUNT_ID || 'your-metaapi-account-id';
  token = environment.TOKEN || 'your-metaapi-token';

  /* Meta */
  domain = environment.DOMAIN || 'agiliumtrade.agiliumtrade.ai';
  symbol = environment.SYMBOL || 'EURUSD';
}

<div class="App">
  <h1>MetaApi + Angular</h1>

  <div class="togglers">
    <app-toggler *ngFor="let example of examples; let i = index"
      [className]="'togglers__item'"
      [items]="example.items"
      [name]="example.name"
      [activeItem]="activeExample$ | async"
      [onClickHandler]="setActiveExample">
    </app-toggler>
  </div>

  <div class="component">
    <ng-container [ngSwitch]="activeExample$ | async">
      <meta-api-rpc *ngSwitchCase="'meta-api.rpc'"
        [accountId]="accountId"
        [domain]="domain"
        [token]="token">
      </meta-api-rpc>

      <meta-api-stream *ngSwitchCase="'meta-api.stream'"
        [accountId]="accountId"
        [domain]="domain"
        [token]="token">
      </meta-api-stream>

      <stream-quotes *ngSwitchCase="'stream-quotes'"
        [accountId]="accountId"
        [symbol]="symbol"
        [domain]="domain"
        [token]="token">
      </stream-quotes>

      <historical-get-candles *ngSwitchCase="'historical.get-candles'"
        [token]="token"
        [accountId]="accountId"
        [symbol]="symbol"
        [domain]="domain">
      </historical-get-candles>

      <historical-get-ticks *ngSwitchCase="'historical.get-ticks'"
        [token]="token"
        [accountId]="accountId"
        [symbol]="symbol"
        [domain]="domain">
      </historical-get-ticks>

      <risk-management-period-statistics-stream *ngSwitchCase="'risk-management.period-statistics-stream'"
        [accountId]="accountId"
        [domain]="domain"
        [token]="token">
      </risk-management-period-statistics-stream>

      <risk-management-equity-chart-stream *ngSwitchCase="'risk-management.equity-chart-stream'"
        [accountId]="accountId"
        [domain]="domain"
        [token]="token">
      </risk-management-equity-chart-stream>

      <risk-management-equlity-balance *ngSwitchCase="'risk-management.equlity-balance'"
        [accountId]="accountId"
        [domain]="domain"
        [token]="token">
      </risk-management-equlity-balance>

      <risk-management-equity-tracking *ngSwitchCase="'risk-management.equity-tracking'"
        [accountId]="accountId"
        [domain]="domain"
        [token]="token">
      </risk-management-equity-tracking>

      <meta-stats-get-open-trades *ngSwitchCase="'meta-stats.get-open-trades'"
        [token]="token"
        [accountId]="accountId"
        [domain]="domain">
      </meta-stats-get-open-trades>

      <meta-stats-get-trades *ngSwitchCase="'meta-stats.get-trades'"
        [token]="token"
        [accountId]="accountId"
        [domain]="domain">
      </meta-stats-get-trades>

      <meta-stats-get-metrics *ngSwitchCase="'meta-stats.get-metrics'"
        [token]="token"
        [accountId]="accountId"
        [domain]="domain">
      </meta-stats-get-metrics>

      <copy-factory-external-signal *ngSwitchCase="'copy-factory.external-signal'"
        [providerAccountId]="providerAccountId"
        [subscriberAccountId]="subscriberAccountId"
        [token]="token"
        [domain]="domain">
      </copy-factory-external-signal>

      <copy-factory-stopout-listener *ngSwitchCase="'copy-factory.stopout-listener'"
        [token]="token"
        [domain]="domain">
      </copy-factory-stopout-listener>

      <copy-factory-copy-trade *ngSwitchCase="'copy-factory.copy-trade'"
        [token]="token"
        [providerAccountId]="providerAccountId"
        [subscriberAccountId]="subscriberAccountId"
        [domain]="domain">
      </copy-factory-copy-trade>

      <copy-factory-strategy-transaction-listener *ngSwitchCase="'copy-factory.strategy-transaction-listener'"
        [token]="token"
        [strategyId]="strategyId"
        [domain]="domain">
      </copy-factory-strategy-transaction-listener>

      <copy-factory-strategy-user-log-listener *ngSwitchCase="'copy-factory.strategy-user-log-listener'"
        [token]="token"
        [strategyId]="strategyId"
        [domain]="domain">
      </copy-factory-strategy-user-log-listener>

      <copy-factory-subscriber-transaction-listener *ngSwitchCase="'copy-factory.subscriber-transaction-listener'"
        [token]="token"
        [subscriberAccountId]="subscriberAccountId"
        [domain]="domain">
      </copy-factory-subscriber-transaction-listener>

      <copy-factory-subscriber-user-log-listener *ngSwitchCase="'copy-factory.subscriber-user-log-listener'"
        [token]="token"
        [subscriberAccountId]="subscriberAccountId"
        [domain]="domain">
      </copy-factory-subscriber-user-log-listener>

      <copy-factory-telegram *ngSwitchCase="'copy-factory.telegram'"
        [token]="token"
        [domain]="domain"
        [botToken]="botToken"
        [chatId]="chatId"
        [providerAccountId]="providerAccountId">
      </copy-factory-telegram>
    </ng-container> 
  </div>
</div>
