// examples/angular/app/src/app/app.component.ts
import { BehaviorSubject } from 'rxjs';
import { Component } from '@angular/core';
import { environment } from './environment/environment';

interface IExample {
  name: string
  items: string[]
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  activeExample$ = new BehaviorSubject<string>('metaapi.rpc');
  setActiveExample = (example: string) => {
    this.activeExample$.next(example);
  }

  examples: IExample[] = [
    {
      name: 'MetaApi',
      items: [
        'metaapi.stream',
        'metaapi.rpc',
        'historical.getCandles',
        'historical.getTicks',
        'streamQuotes'
      ]
    }, {
      name: 'Risk Management',
      items: [
        'riskManagement.periodStatisticsStream',
        'riskManagement.equityChartStream',
        'riskManagement.equlityBalance',
        'riskManagement.equityTracking'
      ]
    }, {
      name: 'Copy Factory',
      items: [
        'copyfactory.externalSignal',
        'copyfactory.stopoutListener',
        'copyfactory.copyTrade',
        'copyfactory.strategyTransactionListener',
        'copyfactory.strategyUserLogListener',
        'copyfactory.subscriberTransactionListener',
        'copyfactory.subscriberUserLogListener',
        'copyfactory.telegram',
        'copyfactory.webhooks'
      ]
    }, {
      name: 'Meta Stats',
      items: [
        'metastats.getOpenTrades',
        'metastats.getTrades',
        'metastats.getMetrics',
      ]
    }
  ];

  /* For CopyFactory */
  providerAccountId = environment.PROVIDER_ACCOUNT_ID || 'your-provider-account-id';
  subscriberAccountId = environment.SUBSCRIBER_ACCOUNT_ID || 'your-subscriber-account-id';
  strategyId = environment.STRATEGY_ID || 'your-strategy-id';
  botToken = environment.TELEGRAM_BOT_TOKEN || 'your-telegram-bot-token';
  chatId = environment.TELEGRAM_CHAT_ID || 'your-telegram-chat-id';

  /* For MetaApi */
  accountId = environment.ACCOUNT_ID || 'your-metaapi-account-id';
  token = environment.TOKEN || 'your-metaapi-token';

  /* Meta */
  domain = environment.DOMAIN || 'agiliumtrade.agiliumtrade.ai';
  symbol = environment.SYMBOL || 'EURUSD';
}

<div class="App">
  <h1>MetaApi + Angular</h1>

  <div class="togglers">
    <app-toggler *ngFor="let example of examples; let i = index"
      [className]="'togglers__item'"
      [items]="example.items"
      [name]="example.name"
      [activeItem]="activeExample$ | async"
      [onClickHandler]="setActiveExample">
    </app-toggler>
  </div>

  <div class="component">
    <ng-container [ngSwitch]="activeExample$ | async">
      <metaapi-rpc *ngSwitchCase="'metaapi.rpc'"
        [accountId]="accountId"
        [domain]="domain"
        [token]="token">
      </metaapi-rpc>

      <metaapi-stream *ngSwitchCase="'metaapi.stream'"
        [accountId]="accountId"
        [domain]="domain"
        [token]="token">
      </metaapi-stream>

      <streamQuotes *ngSwitchCase="'streamQuotes'"
        [accountId]="accountId"
        [symbol]="symbol"
        [domain]="domain"
        [token]="token">
      </streamQuotes>

      <historical-getCandles *ngSwitchCase="'historical.getCandles'"
        [token]="token"
        [accountId]="accountId"
        [symbol]="symbol"
        [domain]="domain">
      </historical-getCandles>

      <historical-getTicks *ngSwitchCase="'historical.getTicks'"
        [token]="token"
        [accountId]="accountId"
        [symbol]="symbol"
        [domain]="domain">
      </historical-getTicks>

      <riskManagement-periodStatisticsStream *ngSwitchCase="'riskManagement.periodStatisticsStream'"
        [accountId]="accountId"
        [domain]="domain"
        [token]="token">
      </riskManagement-periodStatisticsStream>

      <riskManagement-equityChartStream *ngSwitchCase="'riskManagement.equityChartStream'"
        [accountId]="accountId"
        [domain]="domain"
        [token]="token">
      </riskManagement-equityChartStream>

      <riskManagement-equlityBalance *ngSwitchCase="'riskManagement.equlityBalance'"
        [accountId]="accountId"
        [domain]="domain"
        [token]="token">
      </riskManagement-equlityBalance>

      <riskManagement-equityTracking *ngSwitchCase="'riskManagement.equityTracking'"
        [accountId]="accountId"
        [domain]="domain"
        [token]="token">
      </riskManagement-equityTracking>

      <metastats-getOpenTrades *ngSwitchCase="'metastats.getOpenTrades'"
        [token]="token"
        [accountId]="accountId"
        [domain]="domain">
      </metastats-getOpenTrades>

      <metastats-getTrades *ngSwitchCase="'metastats.getTrades'"
        [token]="token"
        [accountId]="accountId"
        [domain]="domain">
      </metastats-getTrades>

      <metastats-getMetrics *ngSwitchCase="'metastats.getMetrics'"
        [token]="token"
        [accountId]="accountId"
        [domain]="domain">
      </metastats-getMetrics>

      <copyfactory-externalSignal *ngSwitchCase="'copyfactory.externalSignal'"
        [providerAccountId]="providerAccountId"
        [subscriberAccountId]="subscriberAccountId"
        [token]="token"
        [domain]="domain">
      </copyfactory-externalSignal>

      <copyfactory-stopoutListener *ngSwitchCase="'copyfactory.stopoutListener'"
        [token]="token"
        [domain]="domain">
      </copyfactory-stopoutListener>

      <copyfactory-copyTrade *ngSwitchCase="'copyfactory.copyTrade'"
        [token]="token"
        [providerAccountId]="providerAccountId"
        [subscriberAccountId]="subscriberAccountId"
        [domain]="domain">
      </copyfactory-copyTrade>

      <copyfactory-strategyTransactionListener *ngSwitchCase="'copyfactory.strategyTransactionListener'"
        [token]="token"
        [strategyId]="strategyId"
        [domain]="domain">
      </copyfactory-strategyTransactionListener>

      <copyfactory-strategyUserLogListener *ngSwitchCase="'copyfactory.strategyUserLogListener'"
        [token]="token"
        [strategyId]="strategyId"
        [domain]="domain">
      </copyfactory-strategyUserLogListener>

      <copyfactory-subscriberTransactionListener *ngSwitchCase="'copyfactory.subscriberTransactionListener'"
        [token]="token"
        [subscriberAccountId]="subscriberAccountId"
        [domain]="domain">
      </copyfactory-subscriberTransactionListener>

      <copyfactory-subscriberUserLogListener *ngSwitchCase="'copyfactory.subscriberUserLogListener'"
        [token]="token"
        [subscriberAccountId]="subscriberAccountId"
        [domain]="domain">
      </copyfactory-subscriberUserLogListener>

      <copyfactory-telegram *ngSwitchCase="'copyfactory.telegram'"
        [token]="token"
        [domain]="domain"
        [botToken]="botToken"
        [chatId]="chatId"
        [providerAccountId]="providerAccountId">
      </copyfactory-telegram>

      <copyfactory-webhooks *ngSwitchCase="'copyfactory.webhooks'"
        [token]="token"
        [providerAccountId]="providerAccountId"
        [domain]="domain">
      </copyfactory-webhooks>
    </ng-container>
  </div>
</div>

// examples/react/app/src/App.tsx
/* eslint-disable complexity */
import './App.css';

import { useState } from 'react';

import {
  MetaApiStream,
  MetaApiRpc,
  RiskManagementPeriodStatisticsStream,
  RiskManagementEquityChartStream,
  RiskManagementEqulityBalance,
  RiskManagementEquityTracking,
  HistoricalGetCandles,
  HistoricalGetTicks,
  CopyfactoryExternalSignal,
  CopyfactoryStopoutListener,
  CopyfactoryCopyTrade,
  CopyfactoryStrategyTransactionListener,
  CopyfactoryUserLogListener,
  CopyfactorySubscriberTransactionListener,
  CopyfactorySubscriberUserLogListener,
  CopyfactoryTelegram,
  CopyfactoryWebhooks,
  MetastatsGetOpenTrades,
  MetastatsGetTrades,
  MetastatsGetMetrics,
  StreamQuotes
} from './components';

import { Toggler } from './shared';

interface IExample {
  name: string
  items: string[]
}

const examples: IExample[] = [
  {
    name: 'MetaApi',
    items: [
      'metaapi.stream',
      'metaapi.rpc',
      'historical.getCandles',
      'historical.getTicks',
      'streamQuotes'
    ]
  }, {
    name: 'Risk Management',
    items: [
      'riskManagement.periodStatisticsStream',
      'riskManagement.equityChartStream',
      'riskManagement.equlityBalance',
      'riskManagement.equityTracking'
    ]
  }, {
    name: 'Copy Factory',
    items: [
      'copyfactory.externalSignal',
      'copyfactory.stopoutListener',
      'copyfactory.copyTrade',
      'copyfactory.strategyTransactionListener',
      'copyfactory.strategyUserLogListener',
      'copyfactory.subscriberTransactionListener',
      'copyfactory.subscriberUserLogListener',
      'copyfactory.telegram',
      'copyfactory.webhooks'
    ]
  }, {
    name: 'Meta Stats',
    items: [
      'metastats.getOpenTrades',
      'metastats.getTrades',
      'metastats.getMetrics',
    ]
  }
];

/* For Copyfactory */
const providerAccountId = import.meta.env.VITE_PROVIDER_ACCOUNT_ID || 'your-provider-account-id';
const subscriberAccountId = import.meta.env.VITE_SUBSCRIBER_ACCOUNT_ID || 'your-subscriber-account-id';
const strategyId = import.meta.env.VITE_STRATEGY_ID || 'your-strategy-id';
const botToken = import.meta.env.VITE_TELEGRAM_BOT_TOKEN || 'your-telegram-bot-token';
const chatId = import.meta.env.VITE_TELEGRAM_CHAT_ID || 'your-telegram-chat-id';

/* For MetaApi */
const accountId = import.meta.env.VITE_ACCOUNT_ID || 'your-metaapi-account-id';
const token = import.meta.env.VITE_TOKEN || 'your-metaapi-token';

/* Meta */
const domain = import.meta.env.VITE_DOMAIN || 'agiliumtrade.agiliumtrade.ai';
const symbol = import.meta.env.VITE_SYMBOL || 'EURUSD';

function App() {
  const [activeExample, setActiveExamples] = useState<string>('metaapi.rpc');
  
  return (
    <div className="App">
      <h1>MetaApi + React</h1>
      
      <div className="togglers">
        {examples.map(example => <Toggler key={example.name}
          className="togglers__item"
          onClickHandler={(value: string) => setActiveExamples(value)} 
          {...example}
          activeItem={activeExample}
        />)}
      </div>

      <div className="component">
        { (activeExample === 'metaapi.stream') &&
          <MetaApiStream {...{ accountId, domain, token }} /> }
        { (activeExample === 'metaapi.rpc') &&
          <MetaApiRpc {...{ accountId, domain, token }} /> }

        { (activeExample === 'riskManagement.periodStatisticsStream') &&
          <RiskManagementPeriodStatisticsStream {...{ accountId, domain, token }} /> }
        { (activeExample === 'riskManagement.equityChartStream') &&
          <RiskManagementEquityChartStream {...{ accountId, domain, token }} /> }
        { (activeExample === 'riskManagement.equlityBalance') &&
          <RiskManagementEqulityBalance {...{ accountId, domain, token }} /> }
        { (activeExample === 'riskManagement.equityTracking') &&
          <RiskManagementEquityTracking {...{ accountId, domain, token }} /> }

        { (activeExample === 'historical.getCandles') &&
          <HistoricalGetCandles {...{ token, accountId, symbol, domain }} /> }
        { (activeExample === 'historical.getTicks') &&
          <HistoricalGetTicks {...{ token, accountId, symbol, domain }} /> }

        { (activeExample === 'copyfactory.externalSignal') &&
          <CopyfactoryExternalSignal {...{ providerAccountId, subscriberAccountId, token, domain }} /> }
        { (activeExample === 'copyfactory.stopoutListener') &&
          <CopyfactoryStopoutListener {...{ token, domain }} /> }
        { (activeExample === 'copyfactory.copyTrade') &&
          <CopyfactoryCopyTrade {...{ token, providerAccountId, subscriberAccountId, domain }} /> }
        { (activeExample === 'copyfactory.strategyTransactionListener') &&
          <CopyfactoryStrategyTransactionListener {...{ token, strategyId, domain }} /> }
        { (activeExample === 'copyfactory.strategyUserLogListener') &&
          <CopyfactoryUserLogListener {...{ token, strategyId, domain }} /> }
        { (activeExample === 'copyfactory.subscriberTransactionListener') &&
          <CopyfactorySubscriberTransactionListener {...{ token, subscriberAccountId, domain }} /> }
        { (activeExample === 'copyfactory.subscriberUserLogListener') &&
          <CopyfactorySubscriberUserLogListener {...{ token, subscriberAccountId, domain }} /> }
        { (activeExample === 'copyfactory.telegram') &&
          <CopyfactoryTelegram {...{ token, domain, botToken, chatId, providerAccountId }} /> }
        { (activeExample === 'copyfactory.webhooks') &&
          <CopyfactoryWebhooks {...{ token, domain, providerAccountId }} /> }

        { (activeExample === 'metastats.getOpenTrades') &&
          <MetastatsGetOpenTrades {...{ token, accountId, domain }} /> }
        { (activeExample === 'metastats.getTrades') &&
          <MetastatsGetTrades {...{ token, accountId, domain }} /> }
        { (activeExample === 'metastats.getMetrics') &&
          <MetastatsGetMetrics {...{ token, accountId, domain }} /> }

        { (activeExample === 'streamQuotes') &&
          <StreamQuotes {...{ token, accountId, domain, symbol }} /> }        
      </div> 
    </div>
  );
}

export default App;
