// examples/react/app/src/shared/ui/form/form.tsx
import './form.css';

import React from 'react';
import { IFieldProps } from './form.field';

interface IFormProps {
  children: React.ReactNode

  onSubmit: () => void
  onReset?: () => void

  disabled?: boolean
  done?: boolean
}

export function Form({
  children,

  onSubmit,
  onReset,
  
  disabled,
  done,
}: IFormProps) {

  const rFields = React.Children.map(children, (child: React.ReactNode) => {
    if (React.isValidElement<IFieldProps>(child) && child.props.disabled === undefined)
    {return React.cloneElement<IFieldProps>(child, { disabled });}
    return child;
  });

  return (
    <div className="form">
      { rFields }
      
      <div className="buttons">
        <button 
          className={`button ${disabled? 'button--disactive' : 'button--active'}`} 
          onClick={() => onSubmit()}
          disabled={disabled}
        >
          {disabled? (done === undefined? 'Connect' : (done? 'Connected' : 'Connecting...')) : 'Connect'}
        </button>

        { done && onReset && 
          <button
            className="button button--reset"
            onClick={() => onReset()}
          >
            Clear & Reset
          </button>
        } 
      </div>
    </div>
  );
}

// examples/vue/app/src/shared/ui/form/form.vue
<!-- eslint-disable vue/multi-word-component-names -->
<script setup lang="ts">
import { computed } from 'vue';


interface IFormProps {
  onSubmit: () => void
  onReset?: () => void

  disabled?: boolean
  done?: boolean
}

const props = defineProps<IFormProps>();
const buttonLabel = computed(() => {
  if (props.disabled) {
    return props.done === undefined ? 'Connect' : (props.done ? 'Connected' : 'Connecting...');
  } else {
    return 'Connect';
  }
});

</script>

<template>
  <div class="form">
    <slot 
      v-for="(_, slotName) in $slots" 
      :name="slotName" 
      :disabled="disabled" 
    ></slot>

    <div class="buttons">
      <button 
        class="button" 
        :class="{'button--disactive': disabled, 'button--active': !disabled}" 
        @click="onSubmit"
        :disabled="disabled"
      >
        {{ buttonLabel }}
      </button>

      <button
        v-if="done && onReset"
        class="button button--reset"
        @click="onReset"
      >
        Clear & Reset
      </button>
    </div>
  </div>
</template>

<style>
@import './form.css';
</style>
