// examples/vue/app/src/shared/ui/form/form.field.vue
<script setup lang="ts">
export interface IFieldProps {
  label: string
  onChange: (value: string) => void
  value: string
  disabled?: boolean
}

const props = defineProps<IFieldProps>();
const handleInput = (event: Event) => props.onChange((event.target as HTMLInputElement).value);
</script>

<template>
  <label class="field">
    <span>{{label}}</span>
    <input
      :value="value" 
      @input="handleInput" 
      :disabled="disabled" 
      type="text" 
    />
  </label>
</template>

// examples/react/react-app/src/shared/ui/form/form.field.tsx
export interface IFieldProps {
  label: string
  onChange: (value: string) => void
  value: string
  disabled?: boolean
}

export function Field({
  onChange, value, disabled, label
}: IFieldProps) {
  return (
    <label className="field">
      <span>{label}</span>
      <input
        onChange={({ target: { value: v } }) => onChange(v)}  
        value={value} 

        disabled={disabled}
        type="text"
      />
    </label>
  );
}
